name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # 또는 master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22  # 혹은 프로젝트에 맞는 버전

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Docusaurus site
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
